### ISSUE TITLE
Wetterstations Daten in Db pushen

### ISSUE THREAD

**Issue by LucasDegenhardtSeltmann** [LucasDegenhardtSeltmann/OnTopAutomatisierung#21]
Daten der Wetterstationen abrufen und in die Db pushen.

- [x] Testen mit Wunderground API https://docs.google.com/document/d/1eKCnKXI9xnoMGRRzOL1xPCBihNV2rOet08qpE_gArAY/edit
- [x] Empfangen und Senden über den Nginx Webserver

**Comment by TobiasMaximilianAlexandreBasten** [comment]
Per fremder API funktioniert es. Aber wir wollen das direkt an unseren Server senden.
